name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.3
        with:
          node-version: 12
      - run: yarn install
      - run: yarn lerna bootstrap
      - run: yarn lint
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.3
        with:
          node-version: 12
      - run: yarn install
      - run: yarn lerna bootstrap
      - run: yarn test
