name: CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.3
        with:
          node-version: 12
      - run: yarn install
      - run: yarn lerna bootstrap
  build:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - run: yarn lint
  lint:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - run: yarn test
